### PR TITLE
Doc and tests for Particle.spin_type

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
@henryiii, it is not clear where this property is taken from. From the PDG, I guess? I'm here adding doc and tests, extending a bit the function itself, following what seems reasonable to me. Can you point me to the PDG doc where you took `Particle.spin_type` `and `SpinType enum definitions from? Thanks.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
I think this PR can still go in, @henryiii. Then I will proceed and tag a new release.

**Comment by henryiii** [comment]
I'll have to check on this and the other one. I don't think we need to rush a release too fast, I'd like to make sure it works nicely with DecayLanguage first. We can install from git instead of pypi to test.

**Comment by henryiii** [comment]
(I think both these properties came from AmpGen, btw.)

**Comment by eduardo-rodrigues** [comment]
That's a good point. Do not push the merge button if you want to check on SpinType before merging. Else we're good here :-).

**Comment by henryiii** [comment]
I think we can merge. Let's just add the check to issue #71

**Comment by tevans1260** [comment]
I don't think this comes from AmpGen (which in turn, inherits this stuff from MINT). The preferred numbers to store are probably twice the spin (spectroscopy style) and the parity, separately. If you want to combine them to one signed number, that's also fine. Anyway, is this not just taken from the 'J' column of the PDG MC tables + the P -column?

**Comment by eduardo-rodrigues** [comment]
OK, then let's keep `SpinType` is as I can see how to nicely make use of it - trivially find all pseudoscalar charm mesons, for example:
`Particle.from_search_list(lambda p: p.pdgid.is_meson and p.pdgid.has_charm and p.spin_type==SpinType.PseudoScalar)`

**Comment by henryiii** [comment]
Yes, I think it is also part of the printout, and just a computed property.

**Pull request merged**
