### PR TITLE
Adding new particles to complete extended file

### LINKED ISSUE #24: Add missing particles
The following particles need to be added:

| PID     | Name            | C  |
|---------|-----------------|----|
|      21 | g               | 0  |
|      25 | H               | 0  |
|    5332 | Omega(b)        | -  |
|   10221 | f(0)(1370)      | 0  |
|   10553 | h(b)(1P)        | 0  |
|   11112 | Delta(1900)     | -  |
|   11212 | Delta(1900)     | 0  |
|   12122 | Delta(1900)     | +  |
|   12222 | Delta(1900)     | ++ |
|   30553 | Upsilon(2)(1D)  | 0  |
|  103316 | Xi(1950)        | -  |
|  103326 | Xi(1950)        | 0  |
|  104122 | Lambda(c)(2625) | +  |
|  104312 | Xi(c)(2815)     | 0  |
|  104314 | Xi(c)(2790)     | 0  |
|  104322 | Xi(c)(2815)     | +  |
|  104324 | Xi(c)(2790)     | +  |
|  203312 | Xi(1690)        | -  |
|  203316 | Xi(2030)        | -  |
|  203322 | Xi(1690)        | 0  |
|  203326 | Xi(2030)        | 0  |
|  203338 | Omega(2250)     | -  |
|  204126 | Lambda(c)(2880) | +  |
| 1000223 | omega(1420)     | 0  |

### PR DESCRIPTION
**Pull request by henryiii**
Should fix #24.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
It's looking good. A couple of suggestions:
* Add in the header a line of the kind "File generated on February …".
* Several particles occupy multiple lines because of the multiple charge states, say Delta(1900). It might be nicer to have the charge column filled with non-dummy charges, meaning the correct ones.
* BTW, the header could also explain that/why the various columns have dummy entries.

**Comment by eduardo-rodrigues** [comment]
Hi @henryiii, shall we try and push towards the milestones for 0.3.0? Seems this one PR can quickly be finalised :-).

**Comment by henryiii** [comment]
The mass, etc. will remain dummy, but the rest of the blanks need to be filled in... Haven't had time to do it yet.

**Comment by eduardo-rodrigues** [comment]
I've just pushed in an example so that we can converge on what kind of info we're talking about here.

**Comment by eduardo-rodrigues** [comment]
OK, @henryiii, I made a major update to this extension file. The header contains a fair amount of information explaining many of the particle entries. Let me know if anything is unclear.

**Comment by eduardo-rodrigues** [comment]
Ready for review, @henryiii, and for the updates to the CSV files.

**Pull request merged**
