### PR TITLE
ci: publish and adapt to updates of physical constants in hepunits 2.0.0

### PR DESCRIPTION
**Pull request by henryiii**
Forgot to make this PR earlier.

### CODE REVIEW

**Comment by henryiii** [comment]
@eduardo-rodrigues have you seen this failure before? Doesn't seem to be related to the change I made?

**Comment by eduardo-rodrigues** [comment]
Nope, never seen that. Indeed the error seems totally unrelated to this PR. Feel free to merge this and we later see what the new problem is - weird.

**Comment by henryiii** [comment]
Have the tests been updated for the latest hepunits? I expect the newest one is being pulled.

**Comment by eduardo-rodrigues** [comment]
> Have the tests been updated for the latest hepunits? I expect the newest one is being pulled.

Well spotted! It's a rounding change when converting from width to lifetime.

**Comment by eduardo-rodrigues** [comment]
OK, @henryiii, all fixed.

**Pull request merged**
