### PR TITLE
Allow CSV files to have comments starting with #

### PR DESCRIPTION
**Pull request by tamasgal**
This is a straightforward patch to allow CSV to have comments.

A nicer approach which I can of course also quickly implement is to create a wrapper function for `csv.DictReader`.

The aim is to allow version information or other comments to be added to the CSV files.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
I was trying to avoid this but I guess it won't slow the reader a lot. What's your feeling about this @henryiii?

**Comment by tamasgal** [comment]
Well, the amount of data getting parsed is very low and Python is actually really efficient with string parsing and comparisons.

Btw. I ran `py.test` a few hundred times on both the master and on the PR and there is no significant impact on the run time of the full test suite.

**Comment by tamasgal** [comment]
Also if you care about performance I can improve that part with cache functionality if needed. A simple LRU cache decorated wrapper function for `csv.DictReader` would make sure that the parsing only happens once for every single file in the repository during runtime.

**Comment by eduardo-rodrigues** [comment]
I were faster ;-). Thanks! I will get this in tomorrow, then, unless @henryiii has follow-ups. Then I should add some actual comments to the files … You may have noticed that I committed updates in the meantime, and more is to come ...

**Comment by eduardo-rodrigues** [comment]
Did you not rebase instead? Seems you have brought along my latest commits … Anyway, back to work on the package tomorrow ...

**Comment by tamasgal** [comment]
Sorry, I had too much parallel project opened... fixed ;) I do many physics stuff in GitLab and there we "squash commits", which is a basically a rebase on merge. Accidentally missed that here.

**Comment by henryiii** [comment]
I'm working on materials for a mini-course on high performance Python tomorrow, and had just noticed that directly iterating in Python over a file (like is done here) does not impact performance (which is the main reason one might not want to do it this way). Since this is a generator, it doesn't increate the memory usage either. So it's fine with me.

**Comment by eduardo-rodrigues** [comment]
Addresses https://github.com/scikit-hep/particle/issues/190.

**Pull request merged**
