### PR TITLE
chore: minor cleanup and updates

### PR DESCRIPTION
**Pull request by henryiii**
This captures the good parts of #382, without trying to be more clever with config.

### CODE REVIEW

**Comment by henryiii** [comment]
FYI, I'm using `scikit-hep-repo-review` (experimental side project) to evaluate the current status of compliance to the scikit-hep developer guidelines and have addressed the issues shown so far except for isort.

Screen Shot 2022-03-28 at 11 52 46 AM

**Comment by henryiii** [comment]
Okay to go in?

**Comment by henryiii** [comment]
We can always re-add "deprecated", but it was making it harder to install particle on WebAssembly, so I had dropped it since we are literally not currently using it. We can re-add it if we want to use it again, it's just two lines, but adding a dependency just for possible future use isn't really helpful. Removing the `universal=True` setting I would consider important, since it's causing us to produce `py2.py3` filenames for our releases.

**Review by eduardo-rodrigues — APPROVED** [review]

**Comment by eduardo-rodrigues** [comment]
True. Fine, then move forward ...
BTW, you remove
```
[bdist_wheel]
universal = 1
```
but this package *is* a universal package. What's the catch I'm not aware of?

**Comment by henryiii** [comment]
"Universal" package specifically means it runs on Python 2 and Python 3 without changes. That's not true, is it? That's why wheel adds python 2 tags to the wheel names when you set universal=1.

**Pull request merged**
