### PR TITLE
fix attr.s deprecation

### PR DESCRIPTION
**Pull request by HDembinski**
Addresses #226

### CODE REVIEW

**Comment by henryiii** [comment]
You can also drop total_ordering and set these to true. Mostly though we need to set a min attrs version so we don't get broken installs.

**Comment by HDembinski** [comment]
Thanks for looking into this, @henryiii . Anything I could improve?

**Comment by henryiii** [comment]
I don't think so, looks good to me.

**Comment by HDembinski** [comment]
Also here, should we wait for Eduardo to have a look or merge?

**Comment by henryiii** [comment]
@eduardo-rodrigues I was pretty sure you'd like it, I mostly wanted to make sure you were tracking the major changes so you can write the changelog instead of me ;)

**Comment by eduardo-rodrigues** [comment]
Fine, Henry :D.

I need to find a bit more time to finish my big updates for nuclei (some bits will require discussion among us) and then we can make a new major release ...

**Comment by henryiii** [comment]
I'd probably like to make an update to the setup.cfg too before a new release.

**Pull request merged**
