### PR TITLE
Release version 0.4.2

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by henryiii** [comment]
Let me set up the release pipeline (maybe tomorrow), then we'll merge and tag.

**Comment by eduardo-rodrigues** [comment]
Sure. As you prefer. Else I will do things manually, if you're too busy.

**Comment by eduardo-rodrigues** [comment]
@henryiii, shall we try and get this done this week?

**Comment by henryiii** [comment]
I plan to do it in a couple of hours, actually. :)

**Pull request merged**
