### PR TITLE
chore: require Python 3.8+

### PR DESCRIPTION
**Pull request by henryiii**
- **chore: drop Python 3.7, add Python 3.12**

### CODE REVIEW

**Comment by henryiii** [comment]
Time for most jobs is roughly cut in half, from about 30 seconds to 15 seconds.

**Review by eduardo-rodrigues — CHANGES_REQUESTED** [review]
It is time indeed to remove 3.7 support though I had not done it since "no real need". Fair enough at this stage.

I don't really like to have PRs mixing 2 things such as here. Also, I do not like the idea to move to a super new thing that is basically a 1-person project when there is no problem with installing the standard and 100% supported way. I was OK with moving to Ruff as it got huge support, but uv is super new. There simply is no real gain here, just a danger.

**Comment by henryiii** [comment]
Sure, there were two unrelated commits, I just revered the uv one.

If you are talking about uv, it's not a "1-person project"; it has between 5-7 full time developers. It has more GitHub stars than pip. It's had great adoption, including by Jupyter. Nox, tox, Pixi, and build all support it. build-and-inspect-python-package now uses it.

It's also just in CI; if there's an issue, we can remove the letters "uv" and keep going - I'd say there's very little "danger". It cuts the time waiting for a CI result in half, so I wouldn't say "no gain".

If you are referring to `yezz123/setup-uv`, yes, as far as I know, that's a one person project. But it's just downloading uv and optionally setting up an environment, so it's easy to replace if it breaks.

**Comment by eduardo-rodrigues** [comment]
I was indeed talking about yezz123/setup-uv. I see, thanks for the info. Let's then go with uv in a future PR. (Can that be done without yezz123/setup-uv? Otherwise, fine, I trust you.)

**Review by eduardo-rodrigues — APPROVED** [review]
Feel free to merge when happy.

**Pull request merged**
