### PR TITLE
Parity of antibaryons is opposite to that of the corresponding baryons

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Fixes https://github.com/scikit-hep/particle/issues/250.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks again @redeboer for reporting the bug. This PR fixes the issue. Do you want to give it a try? I guess you would welcome a package release asap for usage in your package?

**Comment by redeboer** [comment]
Sure let me check it right away! I have to do some playing around with branches, because we also have some separate PRs going on with regard to implementing `particle`.

**Comment by redeboer** [comment]
Perfect, it works!
Disclaimer: it's [these definitions](https://github.com/ComPWA/expertsystem/blob/0bd1a718f706efb2c012e63d7637d22fa2355b72/expertsystem/particle_list.yml) that I tested against. Before this PR, there were only conflicts for the antibaryons `p~`, `n~`, `Lambda~`. That is fixed with this PR :)

**Comment by redeboer** [comment]
> I guess you would welcome a package release asap for usage in your package?

Yes, that would be cool, thanks a lot for fixing this so quickly!

**Comment by eduardo-rodrigues** [comment]
Thanks for the checks. I will see if I have anything else I can still squeeze in a new release. In any case I proceed later today with the release.

**Comment by redeboer** [comment]
Thanks for the fast, new release :+1:

**Pull request merged**
