### PR TITLE
Readme format change from rst to md

### PR DESCRIPTION
**Pull request by JOTELLECHEA**
I converted the README.rst to README.md I add a contributors section towards the end similar to DecayLanguage repo. I don't which emoji to apply to each contributor.  This is my first contribution to any open source project; any feedback would be great!

### CODE REVIEW

**Comment by JOTELLECHEA** [comment]
I converted the README.rst to README.md I add a contributors section towards the end similar to DecayLanguage repo. I don't which emoji to apply to each contributor. This is my first contribution to any open source project; any feedback would be great!

**Comment by eduardo-rodrigues** [comment]
Hello @JOTELLECHEA, thank you for your interest in the package and your help improving the documentation! This conversion was a long wished thing, but it always got postponed.

Did you check that the rendering is fine and comprehensively replaces the present reST file?

It is indeed very important to acknowldedge contributions as done in many of the Scikit-HEP packages. The section is something I will take care of separately myself, as done in PR https://github.com/scikit-hep/decaylanguage/pull/272 and relatives for the DecayLanguage package. In that respect, remove the HTML table just leaving the placeholder section
```
## Contributors

We hereby acknowledge the contributors that made this project possible ([emoji key](https://allcontributors.org/docs/en/emoji-key)):

This project follows the [all-contributors](https://github.com/all-contributors/all-contributors) specification.
```
and I will act in a follow-up PR.

**Comment by JOTELLECHEA** [comment]
Hello @eduardo-rodrigues, I removed the html table and have double check the README.md file renders is fine and comprehensively replaces the present reST file.

**Review by eduardo-rodrigues — APPROVED** [review]
Many thanks again for this 👍!

**Comment by eduardo-rodrigues** [comment]
The CI is "failing" because of new warnings from Pandas. That is totally unrelated and will be dealt with separately. Merging.

**Comment by eduardo-rodrigues** [comment]
Addressed task https://github.com/scikit-hep/particle/issues/497.

**Pull request merged**
