### PR TITLE
HTML Greek letters to use hex code rather than entity name

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Closes https://github.com/scikit-hep/particle/issues/361.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
See here @admorris for the improvement to better display HTML particle names with Greek letters in SVG.

**Comment by eduardo-rodrigues** [comment]
Of course many tests fail because I pushed prior to getting the tests updated. I will update those asap ...

**Comment by eduardo-rodrigues** [comment]
FYI @henryiii I will merge this in before the hols. Maybe you're still around and can have a look at this short update?

**Comment by henryiii** [comment]
Seems good to me!

**Pull request merged**
