### PR TITLE
Particle (full)names and literals

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Addresses https://github.com/scikit-hep/particle/issues/49 and improves the code and definitions so that what is returned by `Particle(pdgid).programmatic_name` matches in all cases the literals we have defined.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Almost done except for a few corner cases such as K*_J and D_sJ mesons.

**Comment by eduardo-rodrigues** [comment]
Hi @henryiii, @HDembinski, this MR is almost ready to go. I will soon un-WIP once I commit a few updates to literals, notably to deal with some cases such as
```
    Kst_0_1430_0=10311,
    Kst_0_1430_0_bar=-10311,
    Kst_0_1430_plus=10321,
    Kst_0_1430_minus_bar=-10321,
    Dst_s0_2317_plus=10431,
    Dst_s0_2317_minus=-10431,
```
With the new code the literals and the `programmatic_name` will "easily match" if we rather adopt the notations
```
    K_0st_1430_0=10311,
    K_0st_1430_0_bar=-10311,
    K_0st_1430_plus=10321,
    K_0st_1430_minus_bar=-10321,
    D_s0st_2317_plus=10431,
    D_s0st_2317_minus=-10431,
```
This seems just fine to me.
Otherwise one would need to find these cases and move the "*" around a bit when parsing the data tables, which I'm not too keen on, not the least because it requires yet more dedicated "ifs".
Let me know what you think of this MR. Thanks.

**Comment by HDembinski** [comment]
Seems fine to me as well!

**Comment by eduardo-rodrigues** [comment]
Closes https://github.com/scikit-hep/particle/issues/49.

**Pull request merged**
